apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-domain-com
  namespace: portainer
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - portainer.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: portainer-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: portainer-traefik-security
  namespace: portainer
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: portainer-traefik-transport
  namespace: portainer
spec:
  serverName: portainer
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: portainer-traefik-tlsoptions
  namespace: portainer
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-traefik-websecure
  namespace: portainer
  annotations:
    gethomepage.dev/href: "https://portainer.domain.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Portainer Kubernetes UI"
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: portainer.svg
    gethomepage.dev/app: portainer # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Portainer"
    #gethomepage.dev/showStats: "true"
    #gethomepage.dev/widget.type: "portainer"
    #gethomepage.dev/widget.kubernetes: "true"
    #gethomepage.dev/version: "2"
    #gethomepage.dev/alerts: alertmanager
    #gethomepage.dev/widget.url: "https://portainer.domain.com"
    #gethomepage.dev/widget.env: "1"
    #gethomepage.dev/widget.key: PORTAINER_API_KEY
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`portainer.domain.com`)
      services:
      - name: portainer
        port: 9443
        serversTransport: portainer-traefik-transport
      middlewares:
        - name: portainer-traefik-security
  tls:
    secretName: portainer-domain-com
    options:
      name: portainer-traefik-tlsoptions
