apiVersion: v1
kind: Endpoints
metadata:
  name: ceph-cluster
  labels:
    app: ceph
  namespace: monitoring
subsets:
- addresses:
  - ip: xx.xx.xx.xx #IP of pvenode1
    nodeName: cephnode1
  - ip: xx.xx.xx.xx #IP of pvenode2
    nodeName: cephnode2
  - ip: xx.xx.xx.xx #IP of pvenode3
    nodeName: cephnode3
  ports:
  - name: ceph
    port: 9283
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-cluster
  labels:
    app: ceph
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: ceph
    port: 9283
    targetPort: 9283
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-cluster
  namespace: monitoring
  labels:
    app: ceph
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 15s
    port: ceph
    scheme: http
    path: "/metrics"
  jobLabel: ceph-cluster
  selector:
    matchLabels:
      app: ceph
