apiVersion: external-secrets.io/v1alpha1
kind: ClusterPushSecret
metadata:
  name: prova
spec:
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: prova
  refreshTime: "10s"
  pushSecretSpec:
    updatePolicy: Replace
    deletionPolicy: Delete
    refreshInterval: "15s"
    secretStoreRefs:
      - name: vault-backend
        kind: ClusterSecretStore
    selector:
      secret:
        name: prova-secret # secret to push in the selected namespace
    # To get all the key/values
    data:
      - match:
        #secretKey: username # Key of the secret to push
          remoteRef:
            remoteKey: prova # Secret in the Vault
              #property: username # Key in the Vault secret
              #- match:
              #secretKey: password
              #remoteRef:
              #remoteKey: prova
              #property: password
    # To get single Key/Value
    data:
      - match:
          secretKey: username # Key of the secret to push
          remoteRef:
            remoteKey: prova # Secret in the Vault
            property: username # Key in the Vault secret
      - match:
          secretKey: password
          remoteRef:
            remoteKey: prova
            property: password
