services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    container_name: homepage
    networks:
    #  - socket_proxy
    #  - dnet
      - traefik
      - pihole
#    ports:
#      - 3000:3000
    dns:
      - 192.168.4.100
      - 127.0.0.11
    volumes:
      - $CONFIGDIR/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations, see alternative methods
    environment:
      - TZ={$TZ}
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`homepage.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=middlewares-chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
