# General definitions

postgresql:
  install: false

redis:
  install: false

certmanager:
  install: false

registry:
  ingress:
    tls:
      secretName: gitlab-urbaman

nginx-ingress:
  # Disable the deployment of the in-chart NGINX Ingress provider.
  enabled: false

prometheus:
  install: false

# Global definitions

global:

# License
  gitlab:
    license:
      secret: gitlab-license
      key: license

  hosts:
    domain: domain.com
    hostSuffix: staging
    gitlab:
      name: gitlab.domain.com
      https: false
    registry:
      name: registry.domain.com
      https: false
    kas:
      name: kas.domain.com
    pages:
      name: pages.domain.com
      https: false
    ssh: gitlab.domain.com

  pages:
    enabled: true
    objectStore:
      enabled: true
      bucket: gitlab-pages
      connection:
        secret: object-storage
        key: config

# Ingress
  ingress:
    configureCertmanager: false
    enabled: false

# Shell
  shell:
    port: 2232
    tcp: # Probably needed for Traefik?
      proxyProtocol: true # Probably needed for Traefik? default false

# Postgres 
  psql:
    host: psql.example
    password:
      secret: gitlab-postgresql-password
      key: postgres-password
    port: 5432
    database: gitlab
    username: gitlab
  
# Redis
  redis:
    host: redis.example
    auth:
      enabled: true
      secret: gitlab-redis-password
      key: redis-password

# Object Storage
  minio:
    enabled: false
  registry:
    bucket: gitlab-registry-storage
  appConfig:
    lfs:
      bucket: gitlab-lfs-storage
      connection:
        secret: object-storage
        key: connection
    artifacts:
      bucket: gitlab-artifacts-storage
      connection:
        secret: object-storage
        key: connection
    uploads:
      bucket: gitlab-uploads-storage
      connection:
        secret: object-storage
        key: connection
    packages:
      bucket: gitlab-packages-storage
      connection:
        secret: object-storage
        key: connection
    externalDiffs:
      bucket: gitlab-externaldiffs-storage
      connection:
        secret: object-storage
        key: connection
    terraformState:
      bucket: gitlab-terraformstate-storage
      connection:
        secret: object-storage
        key: connection
    dependencyProxy:
      bucket: gitlab-dependencyproxy-storage
      connection:
        secret: object-storage
        key: connection
    ciSecureFiles:
      bucket: gitlab-cisecurefiles-storage
      connection:
        secret: object-storage
        key: connection
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage

# Subcharts

gitlab:

# Webservice
  webservice:
    ingress:
      tls:
        secretName: gitlab-urbaman
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Gitaly
  gitaly:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Exporter
  gitlab-exporter:
    enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Shell
  gitlab-shell:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack
    sshDaemon: gitlab-sshd

# KAS
  kas:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Migrations
  migrations:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Sidekiq
  sidekiq:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabel:
          release: kube-prometheus-stack

# Toolbox - Backups
  toolbox:
    backups:
      cron:
        enabled: true
      objectStorage:
        config:
          secret: storage-config
          key: config
