{
 "title": "Proxmox Backup Server",
 "description": "Proxmox Backup Server from prometheus, pbs exporter and prometheus pushgateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Store", "query": { "query": "label_values(store)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_snapshot_count", "legendFormat": "Store = {{store}}" }
   ]
  },
  {
   "title": "Total Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_size{store=\"$Store\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "pbs_available{store=\"$Store\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "pbs_used{store=\"$Store\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_used{store=\"$Store\"} / pbs_size{store=\"$Store\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total snapshots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_snapshot_count{store=\"$Store\"}",
     "legendFormat": "Store = {{store}}"
    }
   ]
  },
  {
   "title": "Snapshots per VM(id)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_snapshot_vm_count{store=\"$Store\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}