apiVersion: v1
kind: Namespace
metadata:
  name: cloudbeaver
  labels:
    name: cloudbeaver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:latest
          ports:
            - containerPort: 8978
              name: http
          volumeMounts:
          - mountPath: /opt/cloudbeaver/workspace
            name: cloudbeaver-data
      volumes:
      - name: cloudbeaver-data
        persistentVolumeClaim:
          claimName: cloudbeaver-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudbeaver
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  ports:
  - name: http
    port: 8978
    protocol: TCP
    targetPort: http
  selector:
    app: cloudbeaver
  type: ClusterIP 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudbeaver-domain
  namespace: cloudbeaver
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - cloudbeaver.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: cloudbeaver-domain
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-cloudbeaver-https-redirect
  namespace: cloudbeaver
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-cloudbeaver-security
  namespace: cloudbeaver
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-cloudbeaver-transport
  namespace: cloudbeaver
spec:
  serverName: cloudbeaver 
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-cloudbeaver-tlsoptions
  namespace: cloudbeaver
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-cloudbeaver-websecure
  namespace: cloudbeaver 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cloudbeaver.domain.com`)
      services:
        - name: cloudbeaver
          port: 8978
          serversTransport: traefik-cloudbeaver-transport
      middlewares:
        - name: traefik-cloudbeaver-security
  tls:
    secretName: cloudbeaver-domain
    options:
      name: traefik-cloudbeaver-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-cloudbeaver-web
  namespace: cloudbeaver
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`cloudbeaver.domain.com`)
      services:
        - name: cloudbeaver
          port: 8978
      middlewares:
        - name: traefik-cloudbeaver-https-redirect
