{
 "title": "pfSense",
 "description": "Dashboard for Prometheus node_exporter on pfSense (FreeBSD)",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pfSense"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,1h" },
   {
    "name": "cpus",
    "label": "cpus",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=~\"$instance\", job=~\"pfsense.*\"},cpu)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({job=~\"pfsense.*\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   },
   {
    "name": "wan_interface",
    "label": "WAN Interface",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=~\"$instance\", job=~\"pfsense.+\"},device)"
    }
   },
   {
    "name": "lan_interfaces",
    "label": "LAN Interfaces",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=~\"$instance\", job=~\"pfsense.+\", device!~\"enc\\\\d{1}|$wan_interface\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\",mode='idle'}) by (instance)",
     "legendFormat": "# CPUs"
    },
    {
     "expr": "node_memory_size_bytes{instance=~\"$instance\"} - 0",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_swap_size_bytes{instance=~\"$instance\"} - 0",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=~\"/\"} - 0",
     "legendFormat": "Storage"
    },
    {
     "expr": "node_uname_info{instance=~\"$instance\"} -0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$instance\"}[60s])) / count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Load Avg (1m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=~\"$instance\"} + node_memory_wired_bytes{instance=~\"$instance\"}) / node_memory_size_bytes{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Net pkts/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"$instance\"}[$__interval]) +  rate(node_network_transmit_packets_total{instance=~\"$instance\"}[$__interval])) > 0"
    }
   ]
  },
  {
   "title": "WAN Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval]) + rate(node_network_transmit_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval])) *8 > 0",
     "legendFormat": "wan"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\"}) / node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\"} * 100",
     "legendFormat": "storage"
    },
    {
     "expr": "(node_filesystem_files{instance=~\"$instance\",mountpoint=\"/\"} - node_filesystem_files_free{instance=~\"$instance\",mountpoint=\"/\"}) / node_filesystem_files{instance=~\"$instance\",mountpoint=\"/\"} * 100",
     "legendFormat": "inodes"
    }
   ]
  },
  {
   "title": "Load Avg (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Load Avg (15m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Swap Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_memory_swap_in_bytes_total{instance=~\"$instance\"}[$__interval]) + rate(node_memory_swap_out_bytes_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Swap Rate"
    }
   ]
  },
  {
   "title": "Net err/drops / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"$instance\"}[$__interval])) + sum(rate(node_network_transmit_drop_total{instance=~\"$instance\"}[$__interval])) + sum(rate(node_network_receive_errs_total{instance=~\"$instance\"}[$__interval])) + sum(rate(node_network_transmit_errs_total{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Pkt err/drops"
    }
   ]
  },
  {
   "title": "LAN Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(rate(node_network_receive_bytes_total{device=~\"$lan_interfaces\",instance=~\"$instance\"}[$__interval]) + rate(node_network_transmit_bytes_total{device=~\"$lan_interfaces\",instance=~\"$instance\"}[$__interval]))) -(sum(rate(node_network_receive_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval]) + rate(node_network_transmit_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval])))) *8 / 2 > 0",
     "legendFormat": "lan"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__interval])) by (mode))  / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__interval])))  / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_active_bytes{instance=~\"$instance\"}",
     "legendFormat": "Active (Used)"
    },
    {
     "expr": "node_memory_cache_bytes{instance=~\"$instance\"} + node_memory_buffer_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_inactive_bytes{instance=~\"$instance\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_wired_bytes{instance=~\"$instance\"}",
     "legendFormat": "Wired (Kernel)"
    }
   ]
  },
  {
   "title": "WAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$wan_interface\",instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__interval]) * 8 > 0",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__interval]) * 8 > 0",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "Network packets / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "Packets Drops/Network Errors  / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_drop_total{instance=~\"$instance\"}[$__interval]) + \r\nrate(node_network_transmit_errs_total{instance=~\"$instance\"}[$__interval]) + \r\nrate(node_network_receive_drop_total{instance=~\"$instance\"}[$__interval]) + \r\nrate(node_network_receive_errs_total{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Mcast packets / sec $instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "rate(node_network_receive_multicast_total{instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "CPU Usage Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu$cpus usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "repeat": "cpus",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{cpu=\"$cpus\",instance=~\"$instance\",mode!=\"idle\"}[$__interval])) by (mode))  / scalar(count(count(node_cpu_seconds_total{cpu=\"$cpus\",instance=~\"$instance\"}))) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{cpu=\"$cpus\",instance=~\"$instance\",mode!=\"idle\"}[$__interval])))  / scalar(count(count(node_cpu_seconds_total{cpu=\"$cpus\",instance=~\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Context switches / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_context_switches_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Device interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_device_interrupts_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Device interrupts"
    }
   ]
  },
  {
   "title": "Software interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_software_interrupts_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Software interrupts"
    }
   ]
  },
  {
   "title": "Exec forks() / sec",
   "type": "timeseries",
   "description": "Number of fork() calls / sec",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_forks_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Traps / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_traps_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "System calls / sec ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_system_calls_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Syscalls"
    }
   ]
  }
 ]
}