http:
  routers:
    nasshell-rtr:
      rule: "Host(`nasshell.{{env "DOMAINNAME_1"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - middlewares-chain-no-auth
      service: nasshell-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    nasshell-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.1.31:4200"
