apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: code-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: code-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-nvme2tb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
    app.kubernetes.io/name: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
        app.kubernetes.io/name: code-server
    spec:
      volumes:
      - name: code-server-data
        persistentVolumeClaim:
          claimName: code-server-pvc
      containers:
      - image: codercom/code-server:latest
        imagePullPolicy: Always
        name: code-server
        env:
        - name: PASSWORD
          value: "your_password"
        volumeMounts:
          - mountPath: /home/coder
            name: code-server-data
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: code-server-urbaman
  namespace: code-server
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - code-server.urbaman.it
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: code-server-urbaman
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-code-server-https-redirect
  namespace: code-server
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-code-server-security
  namespace: code-server
spec:
  headers:
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-code-server-transport
  namespace: code-server
spec:
  serverName: code-server 
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-code-server-tlsoptions
  namespace: code-server
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-code-server-websecure
  namespace: code-server 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`code-server.urbaman.it`)
      services:
        - name: code-server
          port: 8080
          serversTransport: traefik-code-server-transport
      middlewares:
        - name: traefik-code-server-security
  tls:
    secretName: code-server-urbaman
    options:
      name: traefik-code-server-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-code-server-web
  namespace: code-server
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`code-server.urbaman.it`)
      services:
        - name: code-server
          port: 8080 
      middlewares:
        - name: traefik-code-server-https-redirect