apiVersion: v1
kind: Namespace
metadata:
  name: qr-code-generator
---
apiVersion: v1
kind: Service
metadata:
  name: qr-code-generator
  namespace: qr-code-generator
  labels:
    app: draw.io
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - name: http
    port: 80
  selector:
    app: draw.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-generator
  namespace: qr-code-generator
  labels:
    app: draw.io        
    app.kubernetes.io/name: draw.io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draw.io
  template:
    metadata:
      labels:
        app: draw.io        
        app.kubernetes.io/name: draw.io
    spec:
      containers:
      - image: bizzycolah/qrcode-generator:latest
        imagePullPolicy: IfNotPresent
        name: qr-code-generator
        ports:
        - containerPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qr-code-generator-domain-com
  namespace: qr-code-generator
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - qr-code-generator.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: qr-code-generator-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-qr-code-generator-https-redirect
  namespace: qr-code-generator
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-qr-code-generator-security
  namespace: qr-code-generator
spec:
  headers:
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-qr-code-generator-transport
  namespace: qr-code-generator
spec:
  serverName: qr-code-generator 
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-qr-code-generator-tlsoptions
  namespace: qr-code-generator
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-qr-code-generator-websecure
  namespace: qr-code-generator 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`qr-code-generator.domain.com`)
      services:
        - name: qr-code-generator
          port: 80
          serversTransport: traefik-qr-code-generator-transport
      middlewares:
        - name: traefik-qr-code-generator-security
  tls:
    secretName: qr-code-generator-domain-com
    options:
      name: traefik-qr-code-generator-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-qr-code-generator-web
  namespace: qr-code-generator
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`qr-code-generator.domain.com`)
      services:
        - name: qr-code-generator
          port: 80 
      middlewares:
        - name: traefik-qr-code-generator-https-redirect
