apiVersion: v1
kind: Service
metadata:
  name: kured
  namespace: kube-system
  labels:
    name: kured
spec:
  ports:
    - name: metrics
      port: 8088
      protocol: TCP
      targetPort: metrics
  selector:
    name: kured
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kured-sm
  namespace: monitoring
  labels:
    app: kured
    name: kured
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 60s
    targetPort: 8080
    path: /metrics
    scrapeTimeout: 30s
  jobLabel: kured
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      name: kured