http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    traefik-bouncer:
      plugin:
        bouncer:
          enabled: true
          crowdsecLapiKey: bouncer-enrollment-key
          crowdsecLapiHost: crowdsec:8080
