http:
  routers:
    asustornas1-router:
      rule: "Host(`asustornas1.domain0.com`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers@file
      service: asustornas1-service
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
    hosting1-https-router:
      rule: Host(`domain1.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www|wp-manager)\.domain1\.com`) || Hostregexp(`.+\.domain2\.com`) || Hostregexp(`.+\.domain3\.com`) || Hostregexp(`.+\.domain6\.com`) || Hostregexp(`.+\.domain5\.com`) || Hostregexp(`.+\.domain4\.com`) || Host(`domain2.com`) || Host(`domain3.com`) || Host(`domain6.com`) || Host(`domain5.com`) || Host(`domain4.com`)
      entryPoints:
        - websecure
      middlewares:
        - secure-headers@file
      service: hosting1-https-service
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
        domains:
          - main: "domain1.com"
            sans:
              - "admin.domain1.com"
              - "webmail.domain1.com"
              - "mail.domain1.com"
              - "autodiscover.domain1.com"
              - "autoconfig.domain1.com"
              - "www.domain1.com"
              - "wp-manager.domain1.com"
          - main: "domain2.com"
            sans:
              - "*.domain2.com"
          - main: "domain3.com"
            sans:
              - "*.domain3.com"
          - main: "domain6.com"
            sans:
              - "*.domain6.com"
          - main: "domain5.com"
            sans:
              - "*.domain5.com"
          - main: "domain4.com"
            sans:
              - "*.domain4.com"
    hosting1-usermin-router:
      rule: Host(`domain1.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www|wp-manager)\.domain1\.com`) || Hostregexp(`.+\.domain2\.com`) || Hostregexp(`.+\.domain3\.com`) || Hostregexp(`.+\.domain6\.com`) || Hostregexp(`.+\.domain5\.com`) || Hostregexp(`.+\.domain4\.com`) || Host(`domain2.com`) || Host(`domain3.com`) || Host(`domain6.com`) || Host(`domain5.com`) || Host(`domain4.com`)
      entryPoints:
        - usermin
      middlewares:
        - secure-headers@file
      service: hosting1-usermin-service
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
        domains:
          - main: "domain1.com"
            sans:
              - "admin.domain1.com"
              - "webmail.domain1.com"
              - "mail.domain1.com"
              - "autodiscover.domain1.com"
              - "autoconfig.domain1.com"
              - "www.domain1.com"
              - "wp-manager.domain1.com"
          - main: "domain2.com"
            sans:
              - "*.domain2.com"
          - main: "domain3.com"
            sans:
              - "*.domain3.com"
          - main: "domain6.com"
            sans:
              - "*.domain6.com"
          - main: "domain5.com"
            sans:
              - "*.domain5.com"
          - main: "domain4.com"
            sans:
              - "*.domain4.com"
    hosting1-webmin-router:
      rule: Host(`domain1.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www|wp-manager)\.domain1\.com`) || Hostregexp(`.+\.domain2\.com`) || Hostregexp(`.+\.domain3\.com`) || Hostregexp(`.+\.domain6\.com`) || Hostregexp(`.+\.domain5\.com`) || Hostregexp(`.+\.domain4\.com`) || Host(`domain2.com`) || Host(`domain3.com`) || Host(`domain6.com`) || Host(`domain5.com`) || Host(`domain4.com`)
      entryPoints:
        - webmin
      middlewares:
        - secure-headers@file
      service: hosting1-webmin-service
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
        domains:
          - main: "domain1.com"
            sans:
              - "admin.domain1.com"
              - "webmail.domain1.com"
              - "mail.domain1.com"
              - "autodiscover.domain1.com"
              - "autoconfig.domain1.com"
              - "www.domain1.com"
              - "wp-manager.domain1.com"
          - main: "domain2.com"
            sans:
              - "*.domain2.com"
          - main: "domain3.com"
            sans:
              - "*.domain3.com"
          - main: "domain6.com"
            sans:
              - "*.domain6.com"
          - main: "domain5.com"
            sans:
              - "*.domain5.com"
          - main: "domain4.com"
            sans:
              - "*.domain4.com"
