http:
  services:
    asustornas1-service:
      loadBalancer:
        servers:
          - url: "https://10.0.100.31:8001"
    hosting1-https-service:
      loadBalancer:
        servers:
          - url: "https://10.0.100.16"
    hosting1-usermin-service:
      loadBalancer:
        servers:
          - url: "https://10.0.100.16:2083"
    hosting1-webmin-service:
      loadBalancer:
        servers:
          - url: "https://10.0.100.16:2087"
