http:
  services:
    asustornas1-service:
      loadBalancer:
        servers:
          - url: "https://<ASUSTOR_IP>:8001"
    hosting1-https-service:
      loadBalancer:
        servers:
          - url: "https://<HOSTING-IP>"
    hosting1-usermin-service:
      loadBalancer:
        servers:
          - url: "https://<HOSTING-IP>:2083"
    hosting1-webmin-service:
      loadBalancer:
        servers:
          - url: "https://<HOSTING-IP>:2087"
