apiVersion: v1
kind: Namespace
metadata:
  name: traefik-external
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcards-hosting1
  namespace: traefik-external
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - domain1.com
  - '*.domain1.com'
  - domain2.com
  - '*.domain2.com'
  - domain3.com
  - '*.domain3.com'
  - domain4.com
  - '*.domain4.com'
  - domain5.com
  - '*.domain5.com'
  - domain6.com
  - mail.domain6.com
  - wp-manager.domain6.com
  - www.domain6.com
  - webmail.domain6.com
  - admin.domain6.com
  - autoconfig.domain6.com
  - autodiscover.domain6.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: wildcards-hosting1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: websites-hosting1-svc
  namespace: traefik-external
subsets:
- addresses:
  - ip: <IP>
    nodeName: websites-hosting1-svc
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: websites-hosting1-svc
  namespace: traefik-external
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: webmin-hosting1-svc
  namespace: traefik-external
subsets:
- addresses:
  - ip: <IP>
    nodeName: webmin1-hosting1-svc
  ports:
  - name: webmin
    port: 2087
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webmin-hosting1-svc
  namespace: traefik-external
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: webmin
    port: 443
    targetPort: 2087
---
apiVersion: v1
kind: Endpoints
metadata:
  name: usermin-hosting1-svc
  namespace: traefik-external
subsets:
- addresses:
  - ip: <IP>
    nodeName: usermin1-hosting1-svc
  ports:
  - name: usermin
    port: 2083
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: usermin-hosting1-svc
  namespace: traefik-external
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: usermin
    port: 443
    targetPort: 2083
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-hosting1-secureheaders
  namespace: traefik-external
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
      #    customRequestHeaders:
      #      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-hosting1-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain6-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain6.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-wp-manager-domain6-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "wp-manager.domain6.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain1-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain1.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain2-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain2.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-crm-domain2-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "crm.domain2.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain3-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain3.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain4-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain4.com"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-domain5-transport
  namespace: traefik-external
spec:
  insecureSkipVerify: true
  serverName: "domain5.com"
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-hosting1-tlsoptions
  namespace: traefik-external
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain6-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain6.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www)\.domain6\.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain6-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-wp-manager-domain6-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`wp-manager.domain6.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-wp-manager-domain6-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain1-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain1.com`) || Hostregexp(`.+\.domain1\.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain1-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain3-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain3.com`) || Hostregexp(`.+\.domain3\.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain3-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain2-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain2.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www)\.domain2\.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain2-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-crm-domain2-it-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crm.domain2.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-crm-domain2-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain4-eu-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain4.com`) || Hostregexp(`.+\.domain4\.com`)
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain4-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-domain5-com-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`domain5.com`) || Hostregexp(`.+\.domain5\.com`)  
      services:
        - name: websites-hosting1-svc
          port: 443
          serversTransport: traefik-domain5-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-hosting1-webmin
  namespace: traefik-external
spec:
  entryPoints:
    - webmin
  routes:
    - kind: Rule
      match: Host(`domain6.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www|wp-manager)\.domain6\.com`) || Hostregexp(`.+\.domain1\.com`) || Hostregexp(`.+\.domain3\.com`) || Hostregexp(`.+\.domain2\.com`) || Hostregexp(`.+\.domain5\.com`) || Hostregexp(`.+\.domain4\.com`) || Host(`domain1.com`) || Host(`domain3.com`) || Host(`domain2.com`) || Host(`domain5.com`) || Host(`domain4.com`)
      services:
        - name: webmin-hosting1-svc
          port: 443
          serversTransport: traefik-hosting1-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-hosting1-usermin
  namespace: traefik-external
spec:
  entryPoints:
    - usermin
  routes:
    - kind: Rule
      match: Host(`domain6.com`) || Hostregexp(`^(admin|webmail|mail|autodiscover|autoconfig|www|wp-manager)\.domain6\.com`) || Hostregexp(`.+\.domain1\.com`) || Hostregexp(`.+\.domain3\.com`) || Hostregexp(`.+\.domain2\.com`) || Hostregexp(`.+\.domain5\.com`) || Hostregexp(`.+\.domain4\.com`) || Host(`domain1.com`) || Host(`domain3.com`) || Host(`domain2.com`) || Host(`domain5.com`) || Host(`domain4.com`)
      services:
        - name: usermin-hosting1-svc
          port: 443
          serversTransport: traefik-hosting1-transport
      middlewares:
        - name: traefik-hosting1-secureheaders
  tls:
    secretName: wildcards-hosting1
    options:
      name: traefik-hosting1-tlsoptions
