services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - '/mnt/DockerProd/configs/wazuh/wazuh_indexer_ssl_certs/:/certificates/'
      - '/mnt/DockerProd/configs/wazuh/certs.yml:/config/certs.yml'
