route:
  group_by: ['namespace']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'null'
  routes:
  - receiver: 'null'
    matchers:
      - alertname =~ "InfoInhibitor|Watchdog"
  - receiver: 'mail'
receivers:
  - name: 'null'
  - name: 'mail'
    email_configs:
    - to: 'admin@domain.com'
      from: 'admin@domain.com'
      smarthost: smtp.domain.com:587
      auth_username: 'admin@domain.com'
      auth_identity: 'admin@domain.com'
      auth_password: 'password'
      send_resolved: true
      tls_config:
        insecure_skip_verify: true
      headers:
        subject: 'Prometheus Mail Alerts'
