#version: "3.9"
 
# NETWORKS
networks:
  traefik:
    external: true
  management:
    external: true
  monitoring:
    external: true
  security:
    external: true
  tools:
    external: true
  databases:
    external: true
#  dnet:
#    external: true
 
# SECRETS
secrets:
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
 
# SERVICES

include:
# NETWORK
  # Traefik 3 - Reverse Proxy
  - compose/network/traefik.yaml

# MANAGEMENT
  # Portainer - Docker management
  - compose/management/portainer.yaml

# MONITORING
  # Cadvisor
  - compose/monitoring/cadvisor.yaml
  # Grafana
  - compose/monitoring/grafana.yaml
  # Prometheus
  - compose/monitoring/prometheus.yaml
  # Node-Exporter
  - compose/monitoring/node-exporter.yaml
  # Alertmanager
  - compose/monitoring/alertmanager.yaml
  # Pbs1-Exporter
  - compose/monitoring/pbs1-exporter.yaml
  # MariaDB Exporter
  - compose/monitoring/mariadb-exporter.yaml
  # Postgres Exporter
  - compose/monitoring/postgres-exporter.yaml
  # Redis Exporter for Valkey
  - compose/monitoring/redis-exporter.yaml
  # Dozzle
  - compose/monitoring/dozzle.yaml

# SECURITY
  # Wazuh
  - compose/security/wazuh.yaml
  # Crowdsec
  - compose/security/crowdsec.yaml
  # Crowdsec
  - compose/security/clamav.yaml

# Databases
  # MariaDB
  - compose/databases/mariadb.yaml
  # Postgresql - immich version
  - compose/databases/postgresql.yaml
  # Valkey (Redis)
  - compose/databases/valkey.yaml

# Tools
  # Draw.io
  - compose/tools/drawio.yaml
  # It-Tools
  - compose/tools/it-tools.yaml
  # Stirling PDF
  - compose/tools/stirling-pdf.yaml
  # Exalidraw
  - compose/tools/exalidraw.yaml
  # Immich
  - compose/tools/immich.yaml
  # Collabora
  - compose/tools/collabora.yaml
  # Nextcloud
  - compose/tools/nextcloud.yaml
  # Talk for Nextcloud
  - compose/tools/talk.yaml
  # Loacl-AI
  - compose/tools/local-ai.yaml
