services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest # Use portainer-ee if you have a Business Edition license key
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - management
    command: -H unix:///var/run/docker.sock # # Use Docker Socket Proxy instead for improved security
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # # Use Docker Socket Proxy instead for improved security
      - $DATADIR/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=${TZ}
    labels:
      - "org.label-schema.group=management"
      - "traefik.enable=true"
      - "traefik.docker.network=management"
      # HTTP Routers
      - "traefik.http.routers.portainer-router.entrypoints=websecure"
      - "traefik.http.routers.portainer-router.rule=Host(`portainer.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.portainer-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.portainer-router.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      - homepage.group=Docker
      - homepage.name=Portainer
      - homepage.icon=portainer.svg
      - homepage.href=https://portainer.$DOMAINNAME_1
      - homepage.description=Portainer
      - homepage.showStats=true
      - homepage.widget.type=portainer
      - homepage.widget.url=https://portainer.$DOMAINNAME_1
      - homepage.widget.key=ptr_8vmExIq8sQzCE3vrPtFg8WQ6qKblUN3E/87gDFAtPzY=
      - homepage.widget.env=1
        #- homepage.widget.fields=["field1","field2"] # optiona


