---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Deployment notes:
    - Github:
      - abbr: HL
        href: https://github.com/urbaman/HomeLab

#- Developer:
#    - Github:
#        - abbr: GH
#          href: https://github.com/

#- Social:
#    - Reddit:
#        - abbr: RE
#          href: https://reddit.com/

#- Entertainment:
#    - YouTube:
#        - abbr: YT
#          href: https://youtube.com/
