---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - pfSense1:
        description: pfSense networking
        href: https://pfsense1.domain.com
        icon: pfsense.svg
        widget:
          type: pfsense
          fields: ["load", "memory", "wanStatus", "disk"]
          url: https://pfsense1.domain.com
          version: 2
          headers:
            X-API-Key: <API_KEY>
          wan: ix3

- Management:
    - Proxmox Cluster Node1:
        description: Proxmox VE Cluster
        href: https://pve1.domain.com:8006
        icon: proxmox.svg
        widget:
          type: proxmox
          url: https://pve1.domain.com:8006
          username: <TOKEN_ID>
          password: <API_KEY>
            #node: pve1
    - Proxmox Backup Server:
        description: Proxmox Backup Server
        href: https://pbs1.domain.com:8007
        icon: proxmox.svg
        widget:
          type: proxmoxbackupserver
          url: https://pbs1.domain.com:8007
          username: <TOKEN_ID>
          password: <API_KEY>
    - Asustornas 1:
        description: Asustor NAS
        href: https://asustornas1.domain.com
        icon: asustor.svg
    - Nut 1:
        description: NUT 1
        href: http://<API_KEY>/cgi-bin/nut/upsstats.cgi
        icon: nut.svg
    - Nut 2:
        description: NUT 2
        href: http://<DOMAIN OR IP>/cgi-bin/nut/upsstats.cgi
        icon: nut.svg
    - Nut 3:
        description: NUT 3
        href: http://<DOMAIN OR IP>/cgi-bin/nut/upsstats.cgi
        icon: nut.svg

- Hosting:
    - Virtualmin:
        description: Proxmox VE Cluster
        href: https://www.urbaman.it:2087
        icon: virtualmin.svg
    - Proxmox Mail Gateway:
        description: Proxmox Mail Gateway
        href: https://pmg1.domain.com:8006
        icon: proxmox.svg

- Domotics:
    - Homeassistant:
        description: Homeassistant
        href: http://<DOMAIN OR IP>:8123/lovelace/default_view
        icon: home-assistant.svg
        widget:
          type: homeassistant
          url: http://<DOMAIN OR IP>:8123
          key: <API_KEY>
