# /var/lib/docker is /volume1/.@plugins/AppCentral/docker-ce/docker_lib
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /volume1/.@plugins/AppCentral/docker-ce/docker_lib:/var/lib/docker:ro
#     - /dev/disk/:/dev/disk:ro
#     - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
    devices:
      - /dev/kmsg
#    expose:
#      - 8080
    networks:
      - monitoring
      - pihole
    dns:
      - 192.168.4.100
      - 127.0.0.11
    labels:
      - "org.label-schema.group=monitoring"
