services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - $DASTADIR/grafana:/var/lib/grafana
      - $COFIGDIR/grafana/:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=$TZ
    restart: unless-stopped
    pull_policy: always
    security_opt:
      - no-new-privileges:true
#    expose:
#      - 3000
    dns:
      - 192.168.4.100
      - 127.0.0.11
    networks:
      - monitoring
      - pihole
      - traefik
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.grafana-rtr.entrypoints=websecure"
      - "traefik.http.routers.grafana-rtr.rule=Host(`grafana.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.grafana-rtr.middlewares=middlewares-chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.grafana-rtr.service=grafana-svc"
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"
