services:
  piholeexporter:
    image: ekofr/pihole-exporter:latest
    container_name: piholeexporter
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
#   expose:
#     - 9617
    dns:
      - 192.168.4.100
      - 127.0.0.11
    networks:
      - monitoring
      - pihole
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLEPASSWORD}
      - PIHOLE_PORT=80
    labels:
      - "org.label-schema.group=monitoring"
