---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - $CONFIGDIR/mediaserver/jellyseerr:/config
        #- $DATADIR/mediaserver:/data #optional
    expose:
      - 5055
    restart: unless-stopped
    networks:
      - traefik
      - mediaserver
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=debug
      - PORT=5055
    labels:
      - "org.label-schema.group=mediaserver"
      - "traefik.enable=true"
      - "traefik.docker.network=mediaserver"
      # HTTP Routers
      - "traefik.http.routers.jellyseerr-router.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr-router.rule=Host(`jellyseerr.$DOMAINNAME_1`)" # HostRegexp:jellyseer.${DOMAINNAME_1},{catchall:.*}" # Host(`jellyseer.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.jellyseerr-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.jellyseerr-router.service=jellyseerr-service"
      - "traefik.http.services.jellyseerr-service.loadbalancer.server.port=5055"
