---
services:
  unpackerr:
    image: ghcr.io/hotio/unpackerr:latest
    container_name: unpackerr
    volumes:
      - $CONFIGDIR/mediaserver/unpackerr:/config
      - $DATADIR/mediaserver/torrents/complete:/data #optional
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
    labels:
      - "org.label-schema.group=mediaserver"
      - homepage.group=Media
      - homepage.name=Unpackerr
      - homepage.icon=sh-unpackerr.png
      - homepage.href=
      - homepage.description=Unpackerr
      - homepage.showStats=true
        #- homepage.widget.type=emby
        #- homepage.widget.url=http://emby.home
        #- homepage.widget.key=yourembyapikeyhere
        #- homepage.widget.fields=["field1","field2"] # optional
