services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    container_name: cyberchef
    networks:
      - traefik
      - tools
    environment:
      - TZ={$TZ}
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=tools"
      # HTTP Routers
      - "traefik.http.routers.cyberchef-router.entrypoints=websecure"
      - "traefik.http.routers.cyberchef-router.rule=Host(`cyberchef.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.cyberchef-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.cyberchef-router.service=cyberchef-service"
      - "traefik.http.services.cyberchef-service.loadbalancer.server.port=80"
      - homepage.group=DevOps
      - homepage.name=Cyberchef
      - homepage.icon=cyberchef.svg
      - homepage.href=https://cyberchef.$DOMAINNAME_1
      - homepage.description=Cyberchef
      - homepage.showStats=true
        #- homepage.widget.type=emby
        #- homepage.widget.url=http://emby.home
        #- homepage.widget.key=yourembyapikeyhere
        #- homepage.widget.fields=["field1","field2"] # optiona

