services:
  exalidraw:
    container_name: exalidraw
    image: excalidraw/excalidraw:latest
    pull_policy: always
    networks:
      - traefik
      - tools 
    environment:
      - TZ=${TZ}
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=tools"
      # HTTP Routers
      - "traefik.http.routers.exalidraw-router.entrypoints=websecure"
      - "traefik.http.routers.exalidraw-router.rule=Host(`exalidraw.$DOMAINNAME_1`)" # HostRegexp:exalidraw.${DOMAINNAME_1},{catchall:.*}" # Host(`exalidraw.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.exalidraw-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.exalidraw-router.service=exalidraw-service"
      - "traefik.http.services.exalidraw-service.loadbalancer.server.port=80"

