services:
  freshrss:
    image: freshrss/freshrss 
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    container_name: freshrss
    expose:
      - 80
    networks:
      - traefik
      - tools
      - databases
    environment:
      - TZ=${TZ}
      - CRON_MIN=1,31
    volumes:
      - $CONFIGDIR/freshrss:/var/www/FreshRSS/data
      - $DATADIR/freshrss:/var/www/FreshRSS/extensions
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=tools"
      # HTTP Routers
      - "traefik.http.routers.freshrss-router.entrypoints=websecure"
      - "traefik.http.routers.freshrss-router.rule=Host(`freshrss.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.freshrss-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.freshrss-router.service=freshrss-service"
      - "traefik.http.services.freshrss-service.loadbalancer.server.port=80"

