services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    expose:
      - "5678"
    networks:
      - traefik
      - tools
      - databases
      - monitoring
    environment:
      - TZ={$TZ}
      - GENERIC_TIMEZONE={$TZ}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_POSTGRESDB_PASSWORD}
    volumes:
      - $DATADIR/n8n:/home/node/.n8n
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=tools"
      # HTTP Routers
      - "traefik.http.routers.n8n-router.entrypoints=websecure"
      - "traefik.http.routers.n8n-router.rule=Host(`n8n.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.n8n-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.n8n-router.service=n8n-service"
      - "traefik.http.services.n8n-service.loadbalancer.server.port=5678"
