{
 "title": "Glusterfs",
 "tags": [ "glusterfs" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "brick",
    "label": "brick",
    "query": {
     "query": "label_values(glusterfs_brick_capacity_bytes,path)"
    }
   },
   {
    "name": "volume",
    "label": "volume",
    "query": {
     "query": "label_values(glusterfs_volume_health,name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(glusterfs_node_uptime_seconds,hostname)"
    }
   },
   {
    "name": "subvol",
    "label": "subvol",
    "query": {
     "query": "label_values(glusterfs_subvol_health,subvol_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Glusterd uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glusterfs_glusterd_uptime_seconds{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glusterfs_node_uptime_seconds{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Self Heal uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glusterfs_shd_uptime_seconds{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Oepn file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "glusterfs_process_max_fds", "legendFormat": "Max" },
    { "expr": "glusterfs_process_open_fds", "legendFormat": "Open" }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "glusterfs_process_bytes_since_gc",
     "legendFormat": "Since last"
    },
    {
     "expr": "glusterfs_process_gc_free_bytes",
     "legendFormat": "Free"
    },
    {
     "expr": "glusterfs_process_gc_heap_bytes",
     "legendFormat": "Heap"
    },
    {
     "expr": "glusterfs_process_gc_unmapped_bytes",
     "legendFormat": "Umapped"
    },
    {
     "expr": "glusterfs_process_gc_total_bytes",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_count", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_health", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Brick count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_brick_count", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Replica count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_replica_count", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Snapshot count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_volume_snapshot_count",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Arbiter count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_arbiter_count", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Distribute count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_volume_distribute_count",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disperse count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_volume_disperse_count",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Subvol count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_volume_subvol_count", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_volume_capacity_used_bytes/glusterfs_volume_capacity_bytes",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Inodes usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_volume_inodes_used_count/glusterfs_volume_inodes_count",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Brick Capacity $volume",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "repeat": "volume",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_volume_capacity_bytes{name=~\"$volume\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "glusterfs_volume_capacity_free_bytes{name=~\"$volume\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "glusterfs_volume_capacity_used_bytes{name=~\"$volume\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Subvolumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_subvol_health", "legendFormat": "{{subvol_name}}" }
     ]
    },
    {
     "title": "Brick count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_subvol_brick_count", "legendFormat": "{{subvol_name}}" }
     ]
    },
    {
     "title": "Up Bricks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_subvol_up_bricks", "legendFormat": "{{subvol_name}}" }
     ]
    },
    {
     "title": "Usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_subvol_capacity_used_bytes/glusterfs_subvol_capacity_bytes",
       "legendFormat": "{{subvol_name}}"
      }
     ]
    },
    {
     "title": "Inodes usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_subvol_inodes_used_count/glusterfs_subvol_inodes_count",
       "legendFormat": "{{subvol_name}}"
      }
     ]
    },
    {
     "title": "Brick Capacity $subvol",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "repeat": "subvol",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_subvol_capacity_bytes{subvol_name=~\"$subvol\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "glusterfs_subvol_capacity_free_bytes{subvol_name=~\"$subvol\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "glusterfs_subvol_capacity_used_bytes{subvol_name=~\"$subvol\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Bricks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status $brick",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_brick_health{path=~\"$brick\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "glusterfs_brick_uptime_seconds", "legendFormat": "{{path}}" }
     ]
    },
    {
     "title": "CPU Percentual",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "glusterfs_brick_cpu_percentage", "legendFormat": "{{path}}" }
     ]
    },
    {
     "title": "Memory Percentual",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_brick_memory_percentage",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_brick_capacity_used_bytes/glusterfs_brick_capacity_bytes",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Inodes usage percentual",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "glusterfs_brick_inodes_used_count/glusterfs_brick_inodes_count",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Brick Capacity $brick",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
     "repeat": "brick",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glusterfs_brick_capacity_bytes{path=~\"$brick\", hostname=~\"$node\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "glusterfs_brick_capacity_free_bytes{path=~\"$brick\", hostname=~\"$node\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "glusterfs_brick_capacity_used_bytes{path=~\"$brick\", hostname=~\"$node\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  }
 ]
}