---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings


title: My Homelab Homepage
language: it
showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
headerStyle: boxed

