---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings


title: My Homelab Homepage
language: it
showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
headerStyle: boxed
layout:
  Media:
    style: row
    columns: 2
  Strumenti:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 3

