apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-basic-auth
  namespace: monitoring
data:
  username: <username> 
  password: <password>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptimekuma-sm
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: uptimekuma
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma
      app.kubernetes.io/name: uptime-kuma
  endpoints:
  - port: http 
    interval: 15s
    path: '/metrics'
    basicAuth: # Only needed if authentication is enabled (default)
      username:
        name: uptime-kuma-basic-auth
        key: username
      password:
        name: uptime-kuma-basic-auth
        key: password
