version: "3.9"
 
# NETWORKS
networks:
  traefik:
    external: true
  pihole:
    external: true
  monitoring:
    external: true
#  dnet:
#    external: true
 
# SECRETS
secrets:
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
 
# SERVICES

include:
# NETWORK
  # Traefik 2 - Reverse Proxy
  - compose/network/traefik.yaml

  #Cloudflared DNS DoH
  - compose/network/cloudflared.yaml

  #Pihole DNS DHCP server
  - compose/network/pihole.yaml

  # dchp_helper
  - compose/network/dhcphelper.yaml

# CORE
  # Portainer docker dashboard
  - compose/core/portainer.yaml

  # Dozzle log reader
  - compose/core/dozzle.yaml

  # Homepage
  - compose/core/homepage.yaml

# Monitoring
  # Prometheus
  - compose/monitoring/prometheus.yaml

  # Alertmanager
  - compose/monitoring/alertmanager.yaml

  # Nodeexporter
  - compose/monitoring/nodeexporter.yaml

  # Cadvisor
  - compose/monitoring/cadvisor.yaml

  # Grafana
  - compose/monitoring/grafana.yaml

  # Pushgateway
  - compose/monitoring/pushgateway.yaml

# TOOLS
  # Stirling PDF tools
  - compose/tools/stirling-pdf.yaml

  # IT Tools
  - compose/tools/it-tools.yaml

  # Draw.io
  - compose/tools/drawio.yaml

# Cloud compute
  # Boinc
  - compose/tools/boinc.yaml

# Coding
  # Code Server
  - compose/coding/code-server.yaml
