version: "3.9"

# NETWORKS
networks:
  traefik:
    external: true
  pihole:
    external: true
#  dnet:
#    external: true

# SECRETS
secrets:
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token

# SERVICES
include:
  - compose/stirling-pdf.yaml
