apiVersion: v1
kind: Endpoints
metadata:
  name: haproxy3
  labels:
    app: haproxy3
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.0.50.63
    nodeName: haproxy3
  ports:
  - name: haproxy3
    port: 8404
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy3
  labels:
    app: haproxy3
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: haproxy3
    port: 8404
    targetPort: 8404
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy3
  namespace: monitoring
  labels:
    app: haproxy3
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: haproxy3
    scheme: http
    path: "/metrics"
  jobLabel: haproxy3
  selector:
    matchLabels:
      app: haproxy3
