apiVersion: v1
kind: Endpoints
metadata:
  name: haproxy2
  labels:
    app: haproxy2
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.0.50.62
    nodeName: haproxy2
  ports:
  - name: haproxy2
    port: 8404
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy2
  labels:
    app: haproxy2
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: haproxy2
    port: 8404
    targetPort: 8404
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy2
  namespace: monitoring
  labels:
    app: haproxy2
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: haproxy2
    scheme: http
    path: "/metrics"
  jobLabel: haproxy2
  selector:
    matchLabels:
      app: haproxy2
