restartPolicy: Always

kind: Deployment

image:
  repository: quay.io/prometheus/snmp-exporter
  # if not set appVersion field from Chart.yaml is used
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}

## Provide a namespace to substitude for the namespace on resources
namespaceOverride: ""

## Security context to be added to snmp-exporter pods
securityContext: {}
  # fsGroup: 1000
  # runAsUser: 1000
  # runAsNonRoot: true

## Security context to be added to snmp-exporter containers
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

## Additional labels to add to all resources
customLabels: 
  app: snmp-exporter-arista-switch
  release: kube-prometheus-stack
  # app: snmp-exporter

# config:

extraConfigmapMounts: 
  - name: prometheus-snmp-exporter-arista-switch
    mountPath: /etc/snmp_exporter
      #    subPath: snmp.yml # (optional)
    configMap: prometheus-snmp-exporter-arista-switch
    readOnly: true
    defaultMode: 420

## Additional init containers
# These will be added to the prometheus-snmp-exporter pod.
extraInitContainers: []
  # - name: init-myservice
  #   image: busybox:1.28
  #   command: [ 'sh', '-c', "sleep 10; done" ]

## Additional secret mounts
# Defines additional mounts with secrets. Secrets must be manually created in the namespace.
extraSecretMounts: []
  # - name: secret-files
  #   mountPath: /run/secrets/snmp-exporter
  #   secretName: snmp-exporter-secret-files
  #   readOnly: true
  #   defaultMode: 420

# Additional volumes, e.g. for secrets used in an extraContainer
extraVolumes: []

# Additional volume mounts for snmp-exporter container
extraVolumeMounts: []

## For RBAC support:
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}
  # limits:
  #   memory: 300Mi
  # requests:
  #   memory: 50Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

service:
  annotations: {}
  type: ClusterIP
  port: 9116
  ipDualStack:
    enabled: false
    ipFamilies: ["IPv6", "IPv4"]
    ipFamilyPolicy: "PreferDualStack"

## An Ingress resource can provide name-based virtual hosting and TLS
## termination among other things for CouchDB deployments which are accessed
## from outside the Kubernetes cluster.
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  ## Class name can be set since version 1.18.
  className: ""
  ## Path type is required since version 1.18. Default: ImplementationSpecific.
  pathType: ""
  hosts: []
    # - chart-example.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

podAnnotations: {}

extraArgs: []
#  --history.limit=1000

replicas: 1
## Monitors ConfigMap changes and POSTs to a URL
## Ref: https://github.com/jimmidyson/configmap-reload
##
configmapReload:
  ## configmap-reload container name
  ##
  name: configmap-reload

  ## configmap-reload container image
  ##
  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.71.2
    pullPolicy: IfNotPresent

  ## configmap-reload resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

# Enable this if you're using https://github.com/prometheus-operator/prometheus-operator
# A service monitor will be created per each item in serviceMonitor.params[]
serviceMonitor:
  enabled: true
  # Default value is the namespace the release is deployed to
  namespace: monitoring

  path: /snmp

  # Fall back to the prometheus default unless specified
  # interval: 10s
  scrapeTimeout: 10s
  module:
    - arista_switch
  auth:
    - arista_switch_v3
  #module:
  #  - if_mib
  # Auth used for scraping.
  #auth:
  #  - public_v2

  # Relabelings dynamically rewrite the label set of a target before it gets scraped.
  # Set if defined unless overriden by params.relabelings.
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RelabelConfig
  relabelings: []
    # - sourceLabels: [__address__]
    #   targetLabel: __param_target
    # - sourceLabels: [__param_target]
    #   targetLabel: instance

  # Metric relabeling is applied to samples as the last step before ingestion.
  # Set if defined unless overriden by params.additionalMetricsRelabels.
  additionalMetricsRelabels: {}

  # Label for selecting service monitors as set in Prometheus CRD.
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PrometheusSpec
  selector:
    release: kube-prometheus-stack

  # Retain the job and instance labels of the metrics retrieved by the snmp-exporter
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint
  honorLabels: true

  params: 
    # Human readable URL that will appear in Prometheus / AlertManager
    - name: arista-switch
    # The target that snmp will scrape
      target: xxx.xxx.xxx.xxx
    # Module used for scraping. Overrides value set in serviceMonitor.module
    #   module:
    #     - if_mib
    # Map of labels for ServiceMonitor. Overrides value set in serviceMonitor.selector
    #   labels: {}
          # release: kube-prometheus-stack
    # Scraping interval. Overrides value set in serviceMonitor.interval
      interval: 30s
    # Scrape timeout. Overrides value set in serviceMonitor.scrapeTimeout
      scrapeTimeout: 30s
    # Relabelings. Overrides value set in serviceMonitor.relabelings
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
    # Map of metric labels and values to add. Overrides value set in serviceMonitor.additionalMetricsRelabels
    #   additionalMetricsRelabels: {}

# Extra manifests to deploy as an array
extraManifests: []
  # - |
  #   apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #   labels:
  #     name: prometheus-extra
  #   data:
  #     extra-data: "value"

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

