apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couchdb
  namespace: couchdb
  labels:
    app: prometheus-couchdb-exporter
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    relabelings:
    - action: replace
      sourceLabels: [node_name]
      regex: "couchdb@couchdb-couchdb-0.couchdb-couchdb.couchdb.svc.cluster.local"
      targetLabel: "node_name"
      replacement: "couchdb-couchdb-0"
    - action: replace
      sourceLabels: [node_name]
      regex: "couchdb@couchdb-couchdb-1.couchdb-couchdb.couchdb.svc.cluster.local"
      targetLabel: "node_name"
      replacement: "couchdb-couchdb-1"
    - action: replace
      sourceLabels: [node_name]
      regex: "couchdb@couchdb-couchdb-2.couchdb-couchdb.couchdb.svc.cluster.local"
      targetLabel: "node_name"
      replacement: "couchdb-couchdb-2"
  jobLabel: couchdb
  selector:
    matchLabels:
      app: prometheus-couchdb-exporter