services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - "-docker_only"
        #      - "-housekeeping_interval=30s"
        #      - "-disable_metrics=cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp"
        #      - "-allow_dynamic_housekeeping=false"
      - "-logtostderr"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
    devices:
      - /dev/kmsg
    networks:
      - monitoring
    labels:
      - "org.label-schema.group=monitoring"      
      - "traefik.enable=true"
      - "traefik.docker.network=monitoring"
      # HTTP Routers
      - "traefik.http.routers.cadvisor-router.entrypoints=websecure"
      - "traefik.http.routers.cadvisor-router.rule=Host(`cadvisor.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.cadvisor-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.cadvisor-router.service=cadvisor-service"
      - "traefik.http.services.cadvisor-service.loadbalancer.server.port=8080"

