services:
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pull_policy: always
    environment:
      - TZ=${TZ}
    security_opt:
      - apparmor:unconfined
        #  - no-new-privileges:true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /run/udev/data:/run/udev/data:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.processes'
      - '--collector.interrupts'
      - '--collector.systemd'
      - '--collector.tcpstat'
      - '--log.level=warn'
    restart: unless-stopped
    networks:
      - monitoring
    labels:
      - "org.label-schema.group=monitoring"
