global:
  serverTelemetry:
    prometheusOperator: false

server:
  ingress:
    enabled: false
  standalone:
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }
      storage "file" {
        path = "/vault/data"
      }
      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }
    
  ui:
    enabled: true
  
  serverTelemetry:
    serviceMonitor:
      enabled: true
      selectors:
        release: kube-prometheus-stack
