apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-domain-com
  namespace: vault
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - vault.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: vault-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vault-security
  namespace: vault
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: vault-transport
  namespace: vault
spec:
  serverName: vault
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: vault-tlsoptions
  namespace: vault
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-websecure
  namespace: vault
  annotations:
    gethomepage.dev/href: "https://vault.domain.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Hashicorp Vault"
    gethomepage.dev/group: DevOps
    gethomepage.dev/icon: hashicorp-vault.svg
    gethomepage.dev/app: vault # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Hashicorp Vault"
    #gethomepage.dev/showStats: "true"
    #gethomepage.dev/widget.type: "emby"
    #gethomepage.dev/widget.url: "https://emby.example.com"
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`vault.domain.com`)
    kind: Rule
    services:
    - name: vault
      port: 8200
      serversTransport: vault-transport
    middlewares:
      - name: vault-security
  tls:
    secretName: vault-domain-com
    options:
      name: vault-tlsoptions
