{
 "title": "Uptime Kuma",
 "description": "A dashboard to show the data from the excellent Uptime Kuma project!",
 "tags": [
  "uptimekuma",
  "kubernetes",
  "servicemonitor"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Site Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_status ", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "TLS Certificate Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_cert_is_valid", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(monitor_response_time{}) by (monitor_name)",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  },
  {
   "title": "TLS Certificate Remaining Days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_cert_days_remaining", "legendFormat": "{{ monitor_name }}" }
   ]
  }
 ]
}