apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tenant-urbaman
  namespace: minio
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - minio-tenant.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: minio-tenant-urbaman
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-minio-tenant-security
  namespace: minio
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-minio-tenant-transport
  namespace: minio
spec:
  serverName: minio-tenant 
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-minio-tenant-tlsoptions
  namespace: minio
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minio-tenant-websecure
  namespace: minio
  annotations:
    gethomepage.dev/href: "https://minio-tenant.domain.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Minio Object Storage"
    gethomepage.dev/group: Storage
    gethomepage.dev/icon: minio.svg
    gethomepage.dev/app: minio-tenant # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Minio Object Storage"
    #gethomepage.dev/showStats: "true"
    #gethomepage.dev/widget.type: "emby"
    #gethomepage.dev/widget.url: "https://emby.example.com"
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio-tenant.domain.com`)
      services:
        - name: minio-tenant-console
          port: 9443
          serversTransport: traefik-minio-tenant-transport
      middlewares:
        - name: traefik-minio-tenant-security
  tls:
    secretName: minio-tenant-urbaman
    options:
      name: traefik-minio-tenant-tlsoptions
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-s3-urbaman
  namespace: minio
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - minio-s3.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: minio-s3-urbaman
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-minioapi-security
  namespace: minio
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-minioapi-transport
  namespace: minio
spec:
  serverName: minioapi 
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-minioapi-tlsoptions
  namespace: minio
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minioapi-websecure
  namespace: minio 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio-s3.domain.com`)
      services:
        - name: minio
          port: 443
          serversTransport: traefik-minioapi-transport
      middlewares:
        - name: traefik-minioapi-security
  tls:
    secretName: minio-s3-urbaman
    options:
      name: traefik-minioapi-tlsoptions
