apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-operator-urbaman
  namespace: minio-operator
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - minio-operator.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: minio-operator-urbaman
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-minio-operator-https-redirect
  namespace: minio-operator
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-minio-operator-security
  namespace: minio-operator
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-minio-operator-transport
  namespace: minio-operator
spec:
  serverName: minio-operator 
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-minio-operator-tlsoptions
  namespace: minio-operator
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minio-operator-websecure
  namespace: minio-operator 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio-operator.domain.com`)
      services:
        - name: console
          port: 9090
            #          serversTransport: traefik-minio-operator-transport
      middlewares:
        - name: traefik-minio-operator-security
  tls:
    secretName: minio-operator-urbaman
    options:
      name: traefik-minio-operator-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minio-operator-web
  namespace: minio-operator
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`minio-operator.domain.com`)
      services:
        - name: console
          port: 9090
      middlewares:
        - name: traefik-minio-operator-https-redirect
