apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniotenant-urbaman
  namespace: urbaminio
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - minio-tenant.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: miniotenant-urbaman
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-miniotenant-https-redirect
  namespace: urbaminio
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-miniotenant-security
  namespace: urbaminio
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-miniotenant-transport
  namespace: urbaminio
spec:
  serverName: miniotenant 
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-miniotenant-tlsoptions
  namespace: urbaminio
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-miniotenant-websecure
  namespace: urbaminio 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio-tenant.domain.com`)
      services:
        - name: urbaminio-console
          port: 9443
          serversTransport: traefik-miniotenant-transport
      middlewares:
        - name: traefik-miniotenant-security
  tls:
    secretName: miniotenant-urbaman
    options:
      name: traefik-miniotenant-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-miniotenant-web
  namespace: urbaminio
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`minio-tenant.domain.com`)
      services:
        - name: urbaminio-console
          port: 9443
      middlewares:
        - name: traefik-miniotenant-https-redirect
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minioapi-urbaman
  namespace: urbaminio
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - minio-s3.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: minioapi-urbaman
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-minioapi-https-redirect
  namespace: urbaminio
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-minioapi-security
  namespace: urbaminio
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-minioapi-transport
  namespace: urbaminio
spec:
  serverName: minioapi 
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-minioapi-tlsoptions
  namespace: urbaminio
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minioapi-websecure
  namespace: urbaminio 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio-s3.domain.com`)
      services:
        - name: minio
          port: 443
          serversTransport: traefik-minioapi-transport
      middlewares:
        - name: traefik-minioapi-security
  tls:
    secretName: minioapi-urbaman
    options:
      name: traefik-minioapi-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-minioapi-web
  namespace: urbaminio
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`minio-s3.domain.com`)
      services:
        - name: minio
          port: 443
      middlewares:
        - name: traefik-minioapi-https-redirect