services:
  # Redis 
  redis:
    container_name: redis
    image: redis:latest
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - database
    environment:
      - TZ=${TZ}
