apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubetail-domain-com
  namespace: kubetail
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - kubetail.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: kubetail-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-kubetail-security
  namespace: kubetail
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-kubetail-transport
  namespace: kubetail
spec:
  serverName: kubetail
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-kubetail-tlsoptions
  namespace: kubetail
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-kubetail-websecure
  namespace: kubetail
  annotations:
    gethomepage.dev/href: "https://kubetail.domain.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Kubernetes Log Viewer"
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: kubernetes-dashboard.svg
    gethomepage.dev/app: kubetail # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Kubetail"
    #gethomepage.dev/showStats: "true"
    #gethomepage.dev/widget.type: "emby"
    #gethomepage.dev/widget.url: "https://emby.example.com"
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kubetail.domain.com`)
      services:
      - name: kubetail-dashboard
        port: 8080
        serversTransport: traefik-kubetail-transport
      middlewares:
        - name: traefik-kubetail-security
  tls:
    secretName: kubetail-domain-com
    options:
      name: traefik-kubetail-tlsoptions
