apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true # enable traefik ingressRoute
  settings.yaml: |
    title: My Homelab Homepage
    language: it
    showStats: true
    statusStyle: "dot"
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      hideVisitURL: true
    headerStyle: boxed
    layout:
      News:
        icon: mdi-newspaper-variant-multiple-outline
        style: row
        columns: 4
        tab: Tools
      Media:
        icon: mdi-multimedia
        style: row
        columns: 4
        tab: Tools
      Tools:
        icon: mdi-tools
        style: row
        columns: 4
        tab: Tools
      Finance:
        icon: mdi-finance
        style: row
        columns: 4
        tab: Tools
      Graphics:
        icon: mdi-draw
        style: row
        columns: 4
        tab: Tools
      Office:
        icon: mdi-office-building-cog-outline
        style: row
        columns: 4
        tab: Tools
      Management:
        icon: mdi-server
        style: row
        columns: 4
        tab: Infrastructure
      Networking:
        icon: mdi-lan
        style: row
        columns: 4
        tab: Infrastructure
      Storage:
        icon: mdi-nas
        style: row
        columns: 4
        tab: Infrastructure
      Security:
        icon: mdi-shield-lock-outline
        style: row
        columns: 4
        tab: Infrastructure
      Kubernetes:
        icon: mdi-docker
        style: row
        columns: 4
        tab: Infrastructure
      DevOps:
        icon: mdi-cog-outline
        style: row
        columns: 4
        tab: Development
      AI & ML:
        icon: mdi-head-lightbulb-outline
        style: row
        columns: 4
        tab: Development
      Monitoring:
        icon: mdi-alert-decagram-outline
        style: row
        columns: 4
        tab: Infrastructure
      Hosting:
        icon: mdi-wan
        style: row
        columns: 4
        tab: Infrastructure
      Domotics:
        icon: mdi-home-automation
        style: row
        columns: 4
        tab: Tools
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Deployment notes:
      - Github:
        - abbr: HL
          href: https://github.com/urbaman/HomeLab
      #- Developer:
      #- Github:
      #  - abbr: GH
      #    href: https://github.com/
  services.yaml: ""
  widgets.yaml: |
    - logo:
        icon: mdi-folder-home-outline
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    #    - resources:
    #        backend: resources
    #        expanded: true
    #        cpu: true
    #        memory: true
    #        network: default
    - search:
        provider: google # google, duckduckgo, bing, baidu, brave or custom
        focus: true # Optional, will set focus to the search bar on page load
        showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
        target: _blank # One of _self, _blank, _parent or _top
    - openmeteo:
        label: Anzola dell'Emilia
        latitude: 44.5473
        longitude: 11.1956
        timezone: Europe/Rome
        units: metric
        cache: 5
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: long
          hourCycle: h23
  docker.yaml: ""
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name:  TZ                       # -- Set the container timezone
              value: Europe/Rome
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.domain.com
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-domain-com
  namespace: homepage
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - homepage.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: homepage-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-homepage-security
  namespace: homepage
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-homepage-transport
  namespace: homepage
spec:
  serverName: homepage
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-homepage-tlsoptions
  namespace: homepage
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-homepage-websecure
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.domain.com`)
      services:
        - name: homepage
          port: 3000
            #          serversTransport: traefik-homepage-transport
      middlewares:
        - name: traefik-homepage-security
  tls:
    secretName: homepage-domain-com
    options:
      name: traefik-homepage-tlsoptions
