apiVersion: v1
kind: Secret
metadata:
  name: pbs-exporter-secrets
  namespace: monitoring
type: Opaque
data:
  PBS_API_TOKEN: <PBS_API_TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbs-exporter
  namespace: monitoring
  labels:
    app: pbs-exporter
    app.kubernetes.io/name: pbs-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbs-exporter
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pbs-exporter
        app.kubernetes.io/name: pbs-exporter
    spec:
      containers:
        - image: ghcr.io/natrontech/pbs-exporter:latest
          name: pbs-exporter
          imagePullPolicy: Always
          user: '65534'
          env:
            - name:  TZ
              value: Europe/Rome
            - name: PBS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: PBS_API_TOKEN
                  name: pbs-exporter-secrets
            - name: PBS_ENDPOINT
              value: "https://pbs1.urbaman.cloud:8007"
            - name: PBS_INSECURE
              value: "false"
            - name: PBS_API_TOKEN_NAME
              value: "exporter"
            - name: PBS_USERNAME
              value: "exporter@pbs"
            - name: PBS_METRICS_PATH
              value: "/pbs1-metrics"
          ports:
           - containerPort: 10019
             name: http
---
apiVersion: v1
kind: Service
metadata:
  name: pbs-exporter
  labels:
    app: pbs-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 10019
      targetPort: 10019
      protocol: TCP
      name: http
  selector:
    app: pbs-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pbs-exporter
  namespace: monitoring
  labels:
    app: pbs-exporter
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: "/pbs1-metrics"
  jobLabel: pbs-exporter
  selector:
    matchLabels:
      app: pbs-exporter