apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cyberchef-domain-com
  namespace: cyberchef
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - cyberchef.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: cyberchef-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cyberchef-security
  namespace: cyberchef
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: cyberchef-transport
  namespace: cyberchef
spec:
  serverName: cyberchef
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cyberchef-tlsoptions
  namespace: cyberchef
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef-websecure
  namespace: cyberchef
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`cyberchef.domain.com`)
    kind: Rule
    services:
    - name: cyberchef
      port: 80 
      serversTransport: cyberchef-transport
    middlewares:
      - name: cyberchef-security
  tls:
    secretName: cyberchef-domain-com
    options:
      name: cyberchef-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef-web
  namespace: cyberchef
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`cyberchef.domain.com`)
    kind: Rule
    services:
    - name: cyberchef
      port: 80
