# microk8s-config.yaml
---
# Set the cluster and services CIDRs
# 'extraKubeProxyArgs' is extra arguments to add to the local node kube-proxy.
# Set a value to null to remove it from the arguments.
version: 0.2.0
addons:
  - name: dns
    args: [10.0.50.3,10.100.0.10]
  - name: ha-cluster
  - name: helm
  - name: helm3
extraCNIEnv:
  IPv4_CLUSTER_CIDR: "10.50.0.0/16"
  IPv4_SERVICE_CIDR: "10.100.0.0/16"
extraSANs:
  - 10.100.0.1
extraKubeAPIServerArgs:
  --etcd-servers: https://etcd.urbaman.it:2379
  --etcd-cafile: ${SNAP_DATA}/certs/etcd-cluster-ca.crt
  --etcd-certfile: ${SNAP_DATA}/certs/etcd-cluster-client.crt
  --etcd-keyfile: ${SNAP_DATA}/certs/etcd-cluster-client.key
  --bind-address: 0.0.0.0