# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - alert-rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - node-exporter:9100

  - job_name: 'traefik'
    static_configs:
      - targets:
        - traefik:8082

  - job_name: 'alertmanager'
    static_configs:
      - targets:
        - alertmanager:9093

  - job_name: 'crowdsec_docker'
    static_configs:
      - targets: ['crowdsec:6060']
        labels:
          machine: 'docker'

  - job_name: 'crowdsec_pfsense'
    static_configs:
      - targets: ['10.0.100.1:6060']
        labels:
          machine: 'pfsense'

  - job_name: 'pfsense'
    static_configs:
      - targets: ['10.0.100.1:9100']
        labels:
          machine: 'pfsense'

  - job_name: 'pbs1'
    static_configs:
      - targets: ['pbs1-exporter:10019']
        labels:
          machine: 'pbs1'

  - job_name: 'pve_cluster'
    metrics_path: "/pve"
    static_configs:
      - targets: ['10.0.100.11:9221'] # ,'10.0.100.12:9221','10.0.100.13:9221']
        labels:
          machine: 'pve_cluster'
    params:
      module: [default]
      cluster: ['1']
      node: ['1']

  - job_name: mariadb
    static_configs:
      - targets: ['mariadb-exporter:9104']
        labels:
          alias: mariadb

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          alias: postgres

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          alias: valkey

  - job_name: minio-job
    bearer_token: <MINIO_KEY1_GENERATED>
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-node
    bearer_token: <MINIO_KEY2_GENERATED>
    metrics_path: /minio/v2/metrics/node
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-bucket
    bearer_token: <MINIO_KEY3_GENERATED>
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-resource
    bearer_token: <MINIO_KEY4_GENERATED>
    metrics_path: /minio/v2/metrics/resource
    static_configs:
    - targets: [minio:9000]

  - job_name: nginx
    static_configs:
      - targets:
        - gitlab:8060
  - job_name: node
    static_configs:
      - targets:
        - gitlab:9100
  - job_name: gitlab-workhorse
    static_configs:
      - targets:
        - gitlab:9229
  - job_name: gitlab-rails
    metrics_path: "/-/metrics"
      #scheme: https
    static_configs:
      - targets:
        - gitlab
  - job_name: gitlab-sidekiq
    static_configs:
      - targets:
        - gitlab:8082
  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
      - targets:
        - gitlab:9168
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - gitlab:9168
  - job_name: gitaly
    static_configs:
      - targets:
        - gitlab:9236
  - job_name: registry
    static_configs:
      - targets:
        - gitlab:5001

  - job_name: netbox
    static_configs:
      - targets:
        - netbox:8080

  - job_name: mongodb
    static_configs:
      - targets:
        - mongodb-exporter:9216

  - job_name: memcached
    static_configs:
      - targets:
        - memcached-exporter:9150
