kind: Namespace
apiVersion: v1
metadata:
  name: fireflyIII
  labels:
    name: fireflyIII
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fireflyIII
  namespace: fireflyIII
  labels:
    app: fireflyIII
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: fireflyIII
  template:
    metadata:
      labels:
        app: fireflyIII
    spec:
      containers:
        - name: fireflyIII
          image: fireflyiii/core:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_KEY
            value: "CHANGEME_32_CHARS"
          - name: DB_HOST
            value: "CHANGEME"
          - name: DB_PORT
            value: "5432"
          - name: DB_CONNECTION
            value: "pgsql"
          - name: DB_DATABASE
            value: "CHANGEME"
          - name: DB_USERNAME
            value: "CHANGEME"
          - name: DB_PASSWORD
            value: "CHANGEME"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/storage/upload
              name: fireflyIII-data
      volumes:
        - name: fireflyIII-data
          persistentVolumeClaim:
            claimName: fireflyIII-pvc
---
kind: Service
metadata:
  name: fireflyIII
  namespace: fireflyIII
  labels:
    app: fireflyIII
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: fireflyIII
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fireflyIII-urbaman
  namespace: fireflyIII
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - fireflyIII.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: fireflyIII-urbaman
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fireflyIII-basic-auth
  namespace: fireflyIII
spec:
  basicAuth:
    secret: fireflyIII-basic-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fireflyIII-https-redirect
  namespace: fireflyIII
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fireflyIII-security
  namespace: fireflyIII
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: fireflyIII-transport
  namespace: fireflyIII
spec:
  serverName: fireflyIII
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: fireflyIII-tlsoptions
  namespace: fireflyIII
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: v1
kind: Secret
metadata:
  name: fireflyIII-basic-auth
  namespace: fireflyIII
data:
  users: |
    YWRtaW46JGFwcjEkZHVjNG9sZ1okNkhOUFJ3ck0vQ0V1WHNMOXd5SDc5MAoK
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fireflyIII-websecure
  namespace: fireflyIII
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fireflyIII.domain.com`)
      services:
        - name: fireflyIII
          port: 80
          serversTransport: fireflyIII-transport
      middlewares:
#        - name: fireflyIII-basic-auth
        - name: fireflyIII-security
  tls:
    secretName: fireflyIII-urbaman
    options:
      name: fireflyIII-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fireflyIII-web
  namespace: fireflyIII
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`fireflyIII.domain.com`)
      services:
        - name: fireflyIII
          port: 80
      middlewares:
        - name: fireflyIII-https-redirect