services:
  dhcphelper:
    container_name: dhcp-helper
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 192.168.4.100
    cap_add:
      - NET_ADMIN
    labels:
      - "org.label-schema.group=monitoring"
