services:
  dockovpn:
    image: alekslitvinenk/openvpn
    container_name: dockovpn
    volumes:
      - $CONFIGDIR/dockovpn:/opt/Dockovpn_data
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
#    user: "1000"
    restart: unless-stopped
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
#    expose:
#      - 3000
    dns:
      - 192.168.4.100
      - 127.0.0.11
    networks:
      - monitoring
      - pihole
      - traefik
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dockovpn-rtr.entrypoints=websecure"
      - "traefik.http.routers.dockovpn-rtr.rule=Host(`dockovpn.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.dockovpn-rtr.middlewares=middlewares-chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.dockovpn-rtr.service=dockovpn-svc"
      - "traefik.http.services.dockovpn-svc.loadbalancer.server.port=8080"
