services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    volumes:
      - $DATADIR/nginx:/data
      - $CONFIGDIR/nginx:/etc/letsencrypt
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
#    user: "1000"
    restart: unless-stopped
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    ports:
      - '8080:80'
      - '8443:443'
#    expose:
#      - 3000
    dns:
      - 192.168.4.100
      - 127.0.0.11
    networks:
      - monitoring
      - pihole
      - traefik
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.nginx-rtr.entrypoints=websecure"
      - "traefik.http.routers.nginx-rtr.rule=Host(`nginx.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.nginx-rtr.middlewares=middlewares-chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.nginx-rtr.service=nginx-svc"
      - "traefik.http.services.nginx-svc.loadbalancer.server.port=81"
