networks:
  tools:
    external: true

services:
  freshrss:
    image: freshrss/freshrss 
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - tools
    environment:
      - TZ=Europe/Rome
      - CRON_MIN=1,31
    volumes:
      - /SwarmVolumes/data/freshrss-data:/var/www/FreshRSS/data
      - /SwarmVolumes/data/freshrss-extensions:/var/www/FreshRSS/extensions
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "org.label-schema.group=tools"
        - "traefik.enable=true"
        - "traefik.swarm.network=tools"
        # HTTP Routers
        - "traefik.http.routers.freshrss-router.entrypoints=websecure"
        - "traefik.http.routers.freshrss-router.rule=Host(`freshrss.domain.com`)"
        # Middlewares
        - "traefik.http.routers.freshrss-router.middlewares=secure-headers@file"
        # HTTP Services
        - "traefik.http.routers.freshrss-router.service=freshrss-service"
        - "traefik.http.services.freshrss-service.loadbalancer.server.port=80"
        - homepage.group=News
        - homepage.name=FreshRSS
        - homepage.icon=freshrss.svg
        - homepage.href=https://freshrss.domain.com
        - homepage.description=FreshRSS
        #- homepage.showStats=true
        - homepage.widget.type=freshrss
        - homepage.widget.url=https://freshrss.domain.com
        - homepage.widget.username=<username>
        - homepage.widget.password=<password>
        #- homepage.widget.fields=["field1","field2"] # optiona


