{
 "title": "CouchDB Dashboard",
 "description": "Please leave a review for me to add if there are anymore necessary for the dashboard to apply. ",
 "tags": [
  "CouchDB",
  "couchdb-exporter"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_name", "query": { "query": "couchdb_database_info" } }
  ]
 },
 "panels": [
  {
   "title": "Selected Couchdb Database Data Size",
   "type": "stat",
   "description": "Selected Couchdb Database Data Size",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_database_data_size{db_name=\"$db_name\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Total number of databases in the cluster",
   "type": "stat",
   "description": "Total number of databases in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(couchdb_httpd_databases_total[5m])"
    }
   ]
  },
  {
   "title": "Number of CouchDB Nodes Available",
   "type": "timeseries",
   "description": "Number of CouchDB Nodes Available",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(couchdb_httpd_node_up)", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "CouchDB HTTPD Requests",
   "type": "stat",
   "description": "Total CouchDB HTTPD Requests per Node",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_requests{node_name=~\".*\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CouchDB HTTP Request per Method",
   "type": "stat",
   "description": "CouchDB HTTP Request per Method per node",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_request_methods{node_name=~\"couchdb.*\",method=~\".*\"}",
     "legendFormat": "{{method}}-{{node_name}}"
    }
   ]
  },
  {
   "title": "CouchDB change_feed",
   "type": "stat",
   "description": "number of clients for continuous _changes per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_clients_requesting_changes{node_name=~\".*\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CouchDB Open Databases",
   "type": "stat",
   "description": "CouchDB Open Databases per Node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_open_databases{node_name=~\".*\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}