apiVersion: v1
kind: Endpoints
metadata:
  name: netbox-service
  labels:
    app: netbox-service
  namespace: traefik-external
subsets:
- addresses:
  - ip: 10.0.50.15
    nodeName: netbox-service
  ports:
  - name: netbox
    port: 443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netbox-service
  labels:
    app: netbox-service
  namespace: traefik-external
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: netbox
    port: 443
    targetPort: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-urbaman
  namespace: traefik-external
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - netbox.urbaman.it
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: netbox-urbaman
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-netbox-https-redirect
  namespace: traefik-external
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-netbox-security
  namespace: traefik-external
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-netbox-transport
  namespace: traefik-external
spec:
  serverName: traefik
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-netbox-tlsoptions
  namespace: traefik-external
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-netbox-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`netbox.urbaman.it`)
      services:
        - name: netbox-service
          port: 443
          serversTransport: traefik-netbox-transport
      middlewares:
        - name: traefik-netbox-security
  tls:
    secretName: netbox-urbaman
    options:
      name: traefik-netbox-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-netbox-web
  namespace: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`netbox.urbaman.it`)
      services:
        - name: netbox-service
          port: 443
      middlewares:
        - name: traefik-netbox-https-redirect
