app_service:
  apps:
  - name: alertmanager
    uri: https://alertmanager.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: prometheus
    uri: https://prometheus.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: grafana
    uri: https://grafana.domain.com
    labels:
      env: monitoring
      context: homelab
    rewrite:
      headers:
      - "Origin: https://grafana.domain.com"
      - "Host: grafana.domain.com"
  - name: pushgateway
    uri: https://pushgateway.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: uptimekuma
    uri: https://uptimekuma.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: semaphore
    uri: https://semaphore.domain.com
    labels:
      env: automation
      context: homelab
  - name: haproxyone
    uri: https://haproxy1.stats.domain.com/stats
    labels:
      env: monitoring
      context: homelab
  - name: haproxytwo
    uri: https://haproxy2.stats.domain.com/stats
    labels:
      env: monitoring
      context: homelab
  - name: haproxythree
    uri: https://haproxy3.stats.domain.com/stats
    labels:
      env: monitoring
      context: homelab
  - name: groundcover
    uri: https://www.groundcover.com/
    labels:
      env: monitoring
      context: homelab
  - name: kubescape
    uri: https://cloud.armosec.io/
    labels:
      env: monitoring
      context: homelab
  - name: traefik
    uri: https://traefik.domain.com
    labels:
      env: management
      context: k8s
  - name: portainer
    uri: https://portainer.domain.com
    labels:
      env: management
      context: k8s
  - name: kubedashboard
    uri: "https://k8dashboard.domain.com/#/login"
    labels:
      env: management
      context: k8s
  - name: longhorn
    uri: https://longhorn.domain.com
    labels:
      env: storage
      context: k8s
  - name: landscapeone
    uri: https://landscape1.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: landscapetwo
    uri: https://landscape2.domain.com
    labels:
      env: monitoring
      context: homelab
  - name: netbox
    uri: https://netbox.domain.com
    labels:
      env: sourceoftruth
      context: homelab
  - name: gethomepage
    uri: https://gethomepage.domain.com
    labels:
      env: dashboard
      context: homelab
  - name: pvenodeone
    uri: https://pvenode1.domain.com:8006
    labels:
      env: hypervisor
      context: homelab
  - name: pvenodetwo
    uri: https://pvenode2.domain.com:8006
    labels:
      env: hypervisor
      context: homelab
  - name: pvenodethree
    uri: https://pvenode3.domain.com:8006
    labels:
      env: hypervisor
      context: homelab
  - name: proxmoxbackupone
    uri: https://pbs1.domain.com:8007
    labels:
      env: backup
      context: homelab
  - name: idracone
    uri: https://10.0.100.21
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: idractwo
    uri: https://10.0.100.22
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: idracthree
    uri: https://10.0.100.23
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: openmanageone
    uri: https://10.0.100.11:1311
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: openmanagetwo
    uri: https://10.0.100.12:1311
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: openmanagethree
    uri: https://10.0.100.13.1311
    labels:
      env: management
      context: homelab
    insecure_skip_verify: true
  - name: pfsenseone
    uri: https://pfsense1.domain.com
    labels:
      env: firewall
      context: homelab
  - name: pfsensetwo
    uri: https://pfsense2.domain.com
    labels:
      env: firewall
      context: homelab
  - name: mysql
    uri: https://mysql.domain.com
    labels:
      env: database
      context: homelab
  - name: mariadb
    uri: https://mariadb.domain.com
    labels:
      env: database
      context: homelab
  - name: dbgate
    uri: https://dbgate.domain.com
    labels:
      env: database
      context: homelab
  - name: cloudbeaver
    uri: https://cloudbeaver.domain.com
    labels:
      env: database
      context: homelab
  - name: pgadmin
    uri: https://pgadmin.domain.com
    labels:
      env: database
      context: homelab
  - name: crouchdb
    uri: https://crouchdb.domain.com
    labels:
      env: database
      context: homelab
  - name: ittools
    uri: https://it-tools.domain.com/
    labels:
      env: webapp
      context: homelab
  - name: spdf
    uri: https://s-pdf.domain.com/
    labels:
      env: webapp
      context: homelab
  - name: drawio
    uri: https://drawio.domain.com
    labels:
      env: webapp
      context: homelab
  - name: actualbudget
    uri: https://budget.domain.com
    labels:
      env: webapp
      context: homelab
  - name: truenas
    uri: https://truenas.domain.com
    labels:
      env: storage
      context: homelab
  - name: miniooperator
    uri: https://minio-operator.domain.com
    labels:
      env: storage
      context: homelab
  - name: miniotenant
    uri: https://minio-tenant.domain.com
    labels:
      env: storage
      context: homelab
  - name: argocd
    uri: https://argocd.domain.com
    labels:
      env: automation
      context: homelab
  - name: vault
    uri: https://vault.domain.com
    labels:
      env: automation
      context: homelab
  - name: gitlab
    uri: https://gitlab.domain.com
    labels:
      env: automation
      context: homelab
  enabled: true
auth_service:
  enabled: false
db_service:
  enabled: false
kubernetes_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: false
teleport:
  join_params:
    method: token
    token_name: /etc/teleport-secrets/auth-token
  log:
    format:
      extra_fields:
      - timestamp
      - level
      - component
      - caller
      output: text
    output: stderr
    severity: INFO
  proxy_server: teleport.domain.com:443
version: v3