apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: postgresql
type: Opaque
data:
  pgadmin-default-password: c2VjcmV0cGFzc3dvcmQ= # This is "secretpassword", change to your password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgresql
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "posgresqladmin@domain.com"
           - name: PGADMIN_DEFAULT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: pgadmin-secret
                 key: pgadmin-default-password
           - name: PGADMIN_PORT
             value: "80"
          ports:
            - containerPort: 80
              name: pgadmin-port
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgresql
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: ClusterIP
  ports:
   - port: 80
     name: pgadmin-port
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-domain
  namespace: postgresql
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - pgadmin.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: pgadmin-domain
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-pgadmin-basic-auth
  namespace: postgresql
spec:
  basicAuth:
    secret: traefik-pgadmin-basic-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-pgadmin-https-redirect
  namespace: postgresql
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-pgadmin-security
  namespace: postgresql
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-pgadmin-transport
  namespace: postgresql
spec:
  serverName: pgadmin 
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-pgadmin-tlsoptions
  namespace: postgresql
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-pgadmin-websecure
  namespace: postgresql 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pgadmin.domain.com`)
      services:
        - name: pgadmin
          port: 80
          serversTransport: traefik-pgadmin-transport
      middlewares:
        - name: traefik-pgadmin-security
  tls:
    secretName: pgadmin-domain
    options:
      name: traefik-pgadmin-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-pgadmin-web
  namespace: postgresql
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`pgadmin.domain.com`)
      services:
        - name: pgadmin
          port: 80
      middlewares:
        - name: traefik-pgadmin-https-redirect