apiVersion: v1
kind: Endpoints
metadata:
  name: asustornas1-service
  namespace: traefik-external
  labels:
    app: asustornas1-service
subsets:
  - addresses:
      - ip: <IP>
    ports:
      - port: 8001
        name: asustornas1
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: asustornas1-service
  namespace: traefik-external
  labels:
    app: asustornas1-service
spec:
  ports:
    - name: asustornas1
      protocol: TCP
      port: 443
      targetPort: 8001
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: asustornas1-domain-com
  namespace: traefik-external
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - asustornas1.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: asustornas1-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-asustornas1-secureheaders
  namespace: traefik-external
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-asustornas1-transport
  namespace: traefik-external
spec:
  serverName: traefik
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-asustornas1-tlsoptions
  namespace: traefik-external
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-asustornas1-websecure
  namespace: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`asustornas1.domain.com`)
      services:
        - name: asustornas1-service
          port: 443
          serversTransport: traefik-asustornas1-transport
      middlewares:
        - name: traefik-asustornas1-secureheaders
  tls:
    secretName: asustornas1-domain-com
    options:
      name: traefik-asustornas1-tlsoptions
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-asustornas1-web
  namespace: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`asustornas1.domain.com`)
      services:
        - name: asustornas1-service
          port: 443
