collabora:

  extra_params: --o:ssl.enable=false --o:ssl.termination=true
  
  existingSecret:
    enabled: true
    secretName: "collabora-auth"
    usernameKey: "username"
    passwordKey: "password"

      #resources:
      #  limits:
      #    cpu: "1800m"
      #    memory: "2000Mi"
      #  requests:
      #    cpu: "1800m"
      #    memory: "2000Mi"

replicaCount: 3

autoscaling:
  enabled: false
      #  minReplicas: 1
      #  maxReplicas: 9
      #  targetCPUUtilizationPercentage: 70
      #  targetMemoryUtilizationPercentage: 50

prometheus:
   servicemonitor:
      enabled: true
      labels:
         release: "kube-prometheus-stack"
   rules:
      enabled: true
      additionalLabels:
         release: "kube-prometheus-stack"
grafana:
   dashboards:
      enabled: true