apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collabora-online-domain
  namespace: collabora-online
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - collabora-online.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: collabora-online-domain
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: collabora-online-https-redirect
  namespace: collabora-online
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: collabora-online-security
  namespace: collabora-online
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: collabora-online-transport
  namespace: collabora-online
spec:
  serverName: collabora-online
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: collabora-online-tlsoptions
  namespace: collabora-online
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-online-websecure
  namespace: collabora-online
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`collabora-online.domain.com`)
    kind: Rule
    services:
    - name: collabora-online
      port: 9980 
      serversTransport: collabora-online-transport
    middlewares:
      - name: collabora-online-security
  tls:
    secretName: collabora-online-domain
    options:
      name: collabora-online-tlsoptions
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-online-web
  namespace: collabora-online
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`collabora-online.domain.com`)
    kind: Rule
    services:
    - name: collabora-online
      port: 9980 
    middlewares:
      - name: collabora-online-https-redirect
