{
 "title": "Typha Dashborad (Calico)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(typha_updates_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "typha_next_breadcrumb_latency_secs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "typha_next_breadcrumb_latency_secs_count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "Client snapshot send",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Client snapshot send count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "client_write_latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_write_latency_secs_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_next_breadcrumb_latency_secs_count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "Typha connections summary",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(typha_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "Accepted connections"
    },
    {
     "expr": "rate(typha_connections_dropped{instance=~\"$instance\"}[5m])",
     "legendFormat": "Dropped connections"
    },
    {
     "expr": "typha_connections_active{instance=~\"$instance\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "typha logs dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_logs_dropped{instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Client snapshot send sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_client_write_latency_secs_sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_write_latency_secs_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "Typha log errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_log_errors{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "kvs and latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Typha kvs msg",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_kvs_per_msg{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "kvs per msg count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_kvs_per_msg_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_ping_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "typha_ping_latency{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "typha_updates_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(typha_updates_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_updates_skipped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(typha_updates_skipped{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "kvs per msg sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_kvs_per_msg_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_ping_latency_sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_ping_latency_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_ping_latency_count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_ping_latency_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  { "title": "General client info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Client latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_latency_secs{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Client latency sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_latency_secs_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "typha_client_write_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "typha_client_write_latency_secs{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Client latency counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_client_latency_secs_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  { "title": "Breadcrumb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Breadcrumb size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "typha_breadcrumb_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Typha breadcrumb block and non block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typha_breadcrumb_block{instance=~\"$instance\"}[5m])",
     "legendFormat": "Block {{instance}} - syncer = {{syncer}}"
    },
    {
     "expr": "rate(typha_breadcrumb_non_block{instance=~\"$instance\"}[5m])",
     "legendFormat": "Non block {{instance}} - syncer = {{syncer}}"
    }
   ]
  },
  {
   "title": "Breadcrumb size count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_breadcrumb_size_count{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "Breadcrumb size sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_breadcrumb_size_sum{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  },
  {
   "title": "Breadcrumb seq number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typha_breadcrumb_seq_number{instance=~\"$instance\"}",
     "legendFormat": "{{syncer}}"
    }
   ]
  }
 ]
}