apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptimekuma-domain-com
  namespace: monitoring
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - uptimekuma.domain.com
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: uptimekuma-domain-com
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: uptimekuma-security
  namespace: monitoring
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: uptimekuma-tlsoptions
  namespace: monitoring
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptimekuma-websecure
  namespace: monitoring
  annotations:
    gethomepage.dev/href: "https://uptimekuma.domain.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Uptimekuma Monitoring"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: uptime-kuma.svg
    gethomepage.dev/app: uptime-kuma # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Uptimekuma"
    #gethomepage.dev/showStats: "true"
    gethomepage.dev/widget.type: "uptimekuma"
    #gethomepage.dev/version: "2"
    #gethomepage.dev/alerts: alertmanager
    gethomepage.dev/widget.url: "https://uptimekuma.domain.com"
    gethomepage.dev/widget.slug: "homepage"
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`uptimekuma.domain.com`)
    kind: Rule
    services:
    - name: uptime-kuma
      port: 3001
    middlewares:
    - name: uptimekuma-security
  tls:
    secretName: uptimekuma-domain-com
    options:
      name: uptimekuma-tlsoptions
      namespace: monitoring
